<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Veldhandleiding voor het beschrijven van bodems bij archeologisch onderzoek in Vlaanderen - 4&nbsp; Beschrijving van bodemhorizonten en -lagen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_classificatie.html" rel="next">
<link href="./03_bodemvorming.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Geen resultaat",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
background: #914f9a;
      }
</style>


<meta name="twitter:title" content="Veldhandleiding voor het beschrijven van bodems bij archeologisch onderzoek in Vlaanderen - 4&nbsp; Beschrijving van bodemhorizonten en -lagen">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://hanecakr.github.io/handleidingBeschrijvenBodems//docs/figuren/cover.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalk in" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_inleiding.html">Veldhandleiding</a></li><li class="breadcrumb-item"><a href="./04_bodembeschrijving.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Beschrijving van bodemhorizonten en -lagen</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalk in" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Beschrijving van bodemhorizonten en -lagen</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./figuren/qr_bodems.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Veldhandleiding voor het beschrijven van bodems bij archeologisch onderzoek in Vlaanderen</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/hanecakr/handleidingBeschrijvenBodems/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Schakel donkere modus in"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Woord vooraf</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./updates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Updates</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Veldhandleiding</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_inleiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Inleiding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_algemeneInfo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Algemene informatie over het onderzoek en de locatie/site</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_bodemvorming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bodemvormende factoren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_bodembeschrijving.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Beschrijving van bodemhorizonten en -lagen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_classificatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Classificatie van het bodemprofiel</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Bronnen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_literatuur.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referenties</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Bijlage</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_CGP5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CGP5</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Op deze pagina</h2>
   
  <ul>
  <li><a href="#oppervlaktestenen" id="toc-oppervlaktestenen" class="nav-link active" data-scroll-target="#oppervlaktestenen"><span class="header-section-number">4.1</span> Oppervlaktestenen</a></li>
  <li><a href="#horizontgrens" id="toc-horizontgrens" class="nav-link" data-scroll-target="#horizontgrens"><span class="header-section-number">4.2</span> Horizontgrens</a>
  <ul>
  <li><a href="#het-nummer-van-de-horizont-aardkundige-eenheid" id="toc-het-nummer-van-de-horizont-aardkundige-eenheid" class="nav-link" data-scroll-target="#het-nummer-van-de-horizont-aardkundige-eenheid"><span class="header-section-number">4.2.1</span> Het nummer van de horizont (aardkundige eenheid)</a></li>
  <li><a href="#de-diepte-ten-opziochte-van-het-maaiveld" id="toc-de-diepte-ten-opziochte-van-het-maaiveld" class="nav-link" data-scroll-target="#de-diepte-ten-opziochte-van-het-maaiveld"><span class="header-section-number">4.2.2</span> De diepte ten opziochte van het maaiveld</a></li>
  <li><a href="#horizontbegrenzing" id="toc-horizontbegrenzing" class="nav-link" data-scroll-target="#horizontbegrenzing"><span class="header-section-number">4.2.3</span> Horizontbegrenzing - duidelijkheid</a></li>
  <li><a href="#horizonttopografie" id="toc-horizonttopografie" class="nav-link" data-scroll-target="#horizonttopografie"><span class="header-section-number">4.2.4</span> Horizonttopografie</a></li>
  </ul></li>
  <li><a href="#bodemvochtigheid" id="toc-bodemvochtigheid" class="nav-link" data-scroll-target="#bodemvochtigheid"><span class="header-section-number">4.3</span> Bodemvochtigheid</a></li>
  <li><a href="#bodemkleur" id="toc-bodemkleur" class="nav-link" data-scroll-target="#bodemkleur"><span class="header-section-number">4.4</span> Bodemkleur</a></li>
  <li><a href="#kleurvlekken" id="toc-kleurvlekken" class="nav-link" data-scroll-target="#kleurvlekken"><span class="header-section-number">4.5</span> Kleurvlekken</a>
  <ul>
  <li><a href="#kleur" id="toc-kleur" class="nav-link" data-scroll-target="#kleur"><span class="header-section-number">4.5.1</span> Kleur</a></li>
  <li><a href="#aantal" id="toc-aantal" class="nav-link" data-scroll-target="#aantal"><span class="header-section-number">4.5.2</span> Aantal</a></li>
  <li><a href="#contrast" id="toc-contrast" class="nav-link" data-scroll-target="#contrast"><span class="header-section-number">4.5.3</span> Contrast</a></li>
  </ul></li>
  <li><a href="#de-benaming-van-de-aardkundige-eenheid-horizontsymbolen" id="toc-de-benaming-van-de-aardkundige-eenheid-horizontsymbolen" class="nav-link" data-scroll-target="#de-benaming-van-de-aardkundige-eenheid-horizontsymbolen"><span class="header-section-number">4.6</span> De benaming van de aardkundige eenheid (horizontsymbolen)</a>
  <ul>
  <li><a href="#benaming" id="toc-benaming" class="nav-link" data-scroll-target="#benaming"><span class="header-section-number">4.6.1</span> Hoofdhorizonten en -lagen (mastersymbolen)</a>
  <ul class="collapse">
  <li><a href="#overgangshorizonten" id="toc-overgangshorizonten" class="nav-link" data-scroll-target="#overgangshorizonten"><span class="header-section-number">4.6.1.1</span> Overgangshorizonten</a></li>
  </ul></li>
  <li><a href="#bijkomende-kenmerken-van-een-horizontlaag-subordinate-symbolen" id="toc-bijkomende-kenmerken-van-een-horizontlaag-subordinate-symbolen" class="nav-link" data-scroll-target="#bijkomende-kenmerken-van-een-horizontlaag-subordinate-symbolen"><span class="header-section-number">4.6.2</span> Bijkomende kenmerken van een horizont/laag (subordinate symbolen)</a></li>
  <li><a href="#vertikale-onderverdelingen" id="toc-vertikale-onderverdelingen" class="nav-link" data-scroll-target="#vertikale-onderverdelingen"><span class="header-section-number">4.6.3</span> Vertikale onderverdelingen</a>
  <ul class="collapse">
  <li><a href="#lithologische-discontinuïteit" id="toc-lithologische-discontinuïteit" class="nav-link" data-scroll-target="#lithologische-discontinuïteit"><span class="header-section-number">4.6.3.1</span> Lithologische discontinuïteit</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#antropogeen-mechanisch-aangevoerd-materiaal" id="toc-antropogeen-mechanisch-aangevoerd-materiaal" class="nav-link" data-scroll-target="#antropogeen-mechanisch-aangevoerd-materiaal"><span class="header-section-number">4.7</span> Antropogeen (mechanisch) aangevoerd materiaal</a>
  <ul>
  <li><a href="#textuur" id="toc-textuur" class="nav-link" data-scroll-target="#textuur"><span class="header-section-number">4.7.1</span> Textuur</a></li>
  <li><a href="#aanwezigheid-van-kleihuidjes" id="toc-aanwezigheid-van-kleihuidjes" class="nav-link" data-scroll-target="#aanwezigheid-van-kleihuidjes"><span class="header-section-number">4.7.2</span> Aanwezigheid van kleihuidjes</a></li>
  </ul></li>
  <li><a href="#grove-fragmenten" id="toc-grove-fragmenten" class="nav-link" data-scroll-target="#grove-fragmenten"><span class="header-section-number">4.8</span> Grove fragmenten</a>
  <ul>
  <li><a href="#type-fragmenten" id="toc-type-fragmenten" class="nav-link" data-scroll-target="#type-fragmenten"><span class="header-section-number">4.8.1</span> Type fragmenten</a></li>
  <li><a href="#distributieverspreiding-van-de-grove-fractie-in-het-profiel" id="toc-distributieverspreiding-van-de-grove-fractie-in-het-profiel" class="nav-link" data-scroll-target="#distributieverspreiding-van-de-grove-fractie-in-het-profiel"><span class="header-section-number">4.8.2</span> Distributie/verspreiding van de grove fractie in het profiel</a></li>
  <li><a href="#cappings-en-pendants" id="toc-cappings-en-pendants" class="nav-link" data-scroll-target="#cappings-en-pendants"><span class="header-section-number">4.8.3</span> Cappings en pendants</a>
  <ul class="collapse">
  <li><a href="#cappings" id="toc-cappings" class="nav-link" data-scroll-target="#cappings"><span class="header-section-number">4.8.3.1</span> Cappings</a></li>
  <li><a href="#pendants" id="toc-pendants" class="nav-link" data-scroll-target="#pendants"><span class="header-section-number">4.8.3.2</span> Pendants</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#bodemstructuur" id="toc-bodemstructuur" class="nav-link" data-scroll-target="#bodemstructuur"><span class="header-section-number">4.9</span> Bodemstructuur</a>
  <ul>
  <li><a href="#types-van-bodemstructuur" id="toc-types-van-bodemstructuur" class="nav-link" data-scroll-target="#types-van-bodemstructuur"><span class="header-section-number">4.9.0.1</span> Types van bodemstructuur</a></li>
  <li><a href="#de-afmetingen" id="toc-de-afmetingen" class="nav-link" data-scroll-target="#de-afmetingen"><span class="header-section-number">4.9.0.2</span> De afmetingen</a></li>
  <li><a href="#de-graad-van-structuurontwikkeling" id="toc-de-graad-van-structuurontwikkeling" class="nav-link" data-scroll-target="#de-graad-van-structuurontwikkeling"><span class="header-section-number">4.9.0.3</span> De graad van structuurontwikkeling</a></li>
  <li><a href="#samengestelde-structuur" id="toc-samengestelde-structuur" class="nav-link" data-scroll-target="#samengestelde-structuur"><span class="header-section-number">4.9.0.4</span> Samengestelde structuur</a></li>
  <li><a href="#cementatie" id="toc-cementatie" class="nav-link" data-scroll-target="#cementatie"><span class="header-section-number">4.9.1</span> Cementatie</a></li>
  <li><a href="#compactie" id="toc-compactie" class="nav-link" data-scroll-target="#compactie"><span class="header-section-number">4.9.2</span> Compactie</a></li>
  <li><a href="#levende-wortels" id="toc-levende-wortels" class="nav-link" data-scroll-target="#levende-wortels"><span class="header-section-number">4.9.3</span> Levende wortels</a>
  <ul class="collapse">
  <li><a href="#aantal-1" id="toc-aantal-1" class="nav-link" data-scroll-target="#aantal-1"><span class="header-section-number">4.9.3.1</span> Aantal</a></li>
  </ul></li>
  <li><a href="#sporen-van-dierenactiviteit" id="toc-sporen-van-dierenactiviteit" class="nav-link" data-scroll-target="#sporen-van-dierenactiviteit"><span class="header-section-number">4.9.4</span> Sporen van dierenactiviteit</a>
  <ul class="collapse">
  <li><a href="#type-van-dierenactiviteit" id="toc-type-van-dierenactiviteit" class="nav-link" data-scroll-target="#type-van-dierenactiviteit"><span class="header-section-number">4.9.4.1</span> Type van dierenactiviteit</a></li>
  <li><a href="#concentratie" id="toc-concentratie" class="nav-link" data-scroll-target="#concentratie"><span class="header-section-number">4.9.4.2</span> Concentratie</a></li>
  <li><a href="#toestand" id="toc-toestand" class="nav-link" data-scroll-target="#toestand"><span class="header-section-number">4.9.4.3</span> Toestand</a></li>
  <li><a href="#geassocieerde-kennmerken" id="toc-geassocieerde-kennmerken" class="nav-link" data-scroll-target="#geassocieerde-kennmerken"><span class="header-section-number">4.9.4.4</span> Geassocieerde kennmerken</a></li>
  </ul></li>
  <li><a href="#kalkreactie-met-hcl-carbonaten" id="toc-kalkreactie-met-hcl-carbonaten" class="nav-link" data-scroll-target="#kalkreactie-met-hcl-carbonaten"><span class="header-section-number">4.9.5</span> Kalkreactie met HCl (carbonaten)</a></li>
  <li><a href="#accumulatie-van-ijzer-en-mangaan" id="toc-accumulatie-van-ijzer-en-mangaan" class="nav-link" data-scroll-target="#accumulatie-van-ijzer-en-mangaan"><span class="header-section-number">4.9.6</span> Accumulatie van ijzer en mangaan</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/hanecakr/handleidingBeschrijvenBodems/edit/main/04_bodembeschrijving.qmd" class="toc-action">Bewerk deze pagina</a></p><p><a href="https://github.com/hanecakr/handleidingBeschrijvenBodems/issues/new" class="toc-action">Een probleem melden</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>Een aantal te beschrijven kenmerken behoren niet tot de minimale set gevraagd in de Code van Goede Praktijk maar kunnen wel belangrijk zijn voor het item ‘andere observaties (mineralen, chemische, biologische en menselijke processen)’ zowel in de profielbeschrijvingen als bij de beschrijvingen van boringen.</p>
<section id="oppervlaktestenen" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="oppervlaktestenen"><span class="header-section-number">4.1</span> Oppervlaktestenen</h2>
<p>Beschrijf de aanwezigheid van gesteenten aan de oppervlakte, al dan niet gedeeltelijk begraven, in termen van percentage oppervlaktedekking, afmetingen, vorm, soort gesteente, graad van verwering etc. Zijn de stenen <em>in situ</em> of door de mens tot op de site gebracht?</p>
<p>Gebruik de volgende indeling (<a href="#tbl-04-01">tabel&nbsp;<span>4.1</span></a>) en schat de twee-dimensionale oppervlakte ingenomen door stenen in met behulp van <a href="#fig-04-14">fig.&nbsp;<span>4.14</span></a>.</p>
<div id="tbl-04-01" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.1: De categorieën voor de concentratie aan oppervlaktestenen.</caption>
<thead>
<tr class="header">
<th>Categorie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geen (0%)</td>
</tr>
<tr class="even">
<td>Zeer weinig (0-2%)</td>
</tr>
<tr class="odd">
<td>Weinig (2-5%)</td>
</tr>
<tr class="even">
<td>Vaak (5-15%)</td>
</tr>
<tr class="odd">
<td>Veel (15-40%)</td>
</tr>
<tr class="even">
<td>Zeer veel (\40%)</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="horizontgrens" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="horizontgrens"><span class="header-section-number">4.2</span> Horizontgrens</h2>
<section id="het-nummer-van-de-horizont-aardkundige-eenheid" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="het-nummer-van-de-horizont-aardkundige-eenheid"><span class="header-section-number">4.2.1</span> Het nummer van de horizont (aardkundige eenheid)</h3>
<p>Geef elke aardkundige eenheid een uniek en vast nummer (1, 2, 3 enz.) na het afbakenen van de horizontgrenzen.</p>
</section>
<section id="de-diepte-ten-opziochte-van-het-maaiveld" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="de-diepte-ten-opziochte-van-het-maaiveld"><span class="header-section-number">4.2.2</span> De diepte ten opziochte van het maaiveld</h3>
<p>Meet de diepte(s) van de boven- en ondergrens van elke aardkundige eenheid in cm vanaf het oppervlak van de minerale bodem (figuur 6). In geval van een schuine begrenzing wordt de hoogste en laagste waarde gegeven. De meeste horizontgrenzen zijn overgangszones in plaats van scherpe grenzen. <em>Let op:</em> noteer (ja/nee) of de onderkant van de diepste horizont bereikt is.</p>
<p>Is er een strooisellaag aanwezig, duid dan de begrenzing van de organische horizonten met negatieve cijfers aan. Deze werkwijze is o.a. zo gekozen omdat de dikte van de strooisellagen (Oi-, Oe-, Oa-horizonten) met de tijd (snel) kan veranderen (zie § <a href="#benaming">4.6</a> voor de uitleg omtrent de horizontsymbolen).</p>
<div id="fig-04-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image21.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.1: Voorbeelden van hoe de horizontdiepte in het veld wordt vastgelegd. Deze diepten zijn belangrijk voor de profielbeschrijving en voor de bemonstering. A) minerale bodem; B) bodem met twee verschillende strooisellagen; C) veenontwikkeling bovenop minerale bodem; D) strooisellaag bovenop veen dat op zijn beurt rust op een minerale bodem. Profiel B kent een schuine einddiepte, hier wordt de hoogste en de laagste waarde aangegeven.</figcaption>
</figure>
</div>
</section>
<section id="horizontbegrenzing" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="horizontbegrenzing"><span class="header-section-number">4.2.3</span> Horizontbegrenzing - duidelijkheid</h3>
<p>De duidelijkheid van de ondergrens van een horizont of laag verwijst naar de dikte van de grenszone tussen aanliggende aardkundige eenheden (tabel 9). Meet de dikte van de overgangszone tussen de twee aanliggende horizonten. Dit is de afstand tussen het punt waar kenmerken van de onderste horizont beginnen en het punt waar de</p>
<p>kenmerken van de bovenste horizont stoppen of anders gesteld de afstand tussen het punt waarin je zeker nog in de bovenliggende horizont bent en het punt waarin je zeker al in de onderliggende horizont bent. In het geval van een recente ploeglaag bijvoorbeeld is dat vaak maar 1 of 2 mm.</p>
<div id="tbl-04-02" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.2: De categorieën van horizontbegrenzing en de dikte van deze begrenzing </caption>
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Categorieën</th>
<th>Dikte grensovergang</th>
<th>Subcategorie</th>
<th>Dikte grensovergang</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Abrupt</td>
<td>0-2 cm</td>
<td>Messcherp</td>
<td>0–0,3 cm</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Zeer scherp</td>
<td>0,3–0,5 cm</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>Scherp</td>
<td>0,5–2,0 cm</td>
</tr>
<tr class="even">
<td>Duidelijk</td>
<td>2-5 cm</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Geleidelijk</td>
<td>5-15 cm</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Diffuus</td>
<td>\15 cm</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
</div>
<p>Voor de categorie ‘Abrupt’ kan ook gekozen worden om de categorie verder te specifiëren volgens de subcategorieën (Messcherp, Zeer Scherp of Scherp).</p>
<p>Bij onderzoek waar de duidelijkheid van de horizontgrens belangrijk is, wordt de exacte dikte van de grensovergang (in cm) best genoteerd.</p>
<blockquote class="blockquote">
<p>Voorbeeld</p>
<p>0.1 cm grens; 1-3 cm grens</p>
</blockquote>
</section>
<section id="horizonttopografie" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="horizonttopografie"><span class="header-section-number">4.2.4</span> Horizonttopografie</h3>
<p>De horizonttopografie geeft de vorm van de grens aan (<a href="#tbl-04-03">tabel&nbsp;<span>4.3</span></a>; <a href="#fig-04-02">fig.&nbsp;<span>4.2</span></a>).</p>
<div id="tbl-04-03" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.3: De categorieën voor de horizonttopografie te omschrijven</caption>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Omschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Recht</td>
<td>Bijna vlak verlopend</td>
</tr>
<tr class="even">
<td>Golvend</td>
<td>Instulpingen minder diep dan breed</td>
</tr>
<tr class="odd">
<td>Onregelmatig</td>
<td>Instulpingen dieper dan breed</td>
</tr>
<tr class="even">
<td>Onderbroken</td>
<td>Discontinu</td>
</tr>
</tbody>
</table>
</div>
<div id="fig-04-02" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image27.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.2: De meest voorkomende horizont-topografieën. A) Recht, B) Golvend, C) Onregelmatig; D) Onderbroken of discontinu (Aangepast naar Schoeneberger et al.&nbsp;2012).</figcaption>
</figure>
</div>
</section>
</section>
<section id="bodemvochtigheid" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="bodemvochtigheid"><span class="header-section-number">4.3</span> Bodemvochtigheid</h2>
<p>Duid per aardkundige eenheid de actuele bodemvochtigheid aan. Aangezien de kleur van een bodem varieert naargelang de vochttoestand, is het belangrijk de conditie waarin de kleur werd bepaald, te noteren. Hieronder vind je een handige veldtest om de vochtigheidsgraad te bepalen (<a href="#tbl-04-04">tabel&nbsp;<span>4.4</span></a>).</p>
<div id="tbl-04-04" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.4: Categorieën om de bodemvochtigheid te bepalen en te omschrijven.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 25%">
<col style="width: 27%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Bij bevochtigen wordt de bodem</th>
<th>Bij wrijven wordt de bodemkleur</th>
<th>Andere kenmerken</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Droog</td>
<td>Donker</td>
<td>Bijna niet lichter</td>
<td></td>
</tr>
<tr class="even">
<td>Licht vochtig</td>
<td>Iets donkerder</td>
<td>Duidelijk lichter</td>
<td>Geen glanzend bodemoppervlakte</td>
</tr>
<tr class="odd">
<td>Vochtig</td>
<td>Geen verandering</td>
<td>Duidelijk lichter</td>
<td>Zwak glanzend bodemoppervlakte</td>
</tr>
<tr class="even">
<td>Nat</td>
<td>Geen verandering</td>
<td>Geen verandering</td>
<td>Glanzend bodemoppervlakte; waterverzadigd</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="bodemkleur" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="bodemkleur"><span class="header-section-number">4.4</span> Bodemkleur</h2>
<p>Kleur is één van de belangrijkste bodemkenmerken voor aardkundig onderzoek. Het is het eerste kenmerk dat je ziet en het is het voornaamste kenmerk waarop je steunt om de aardkundige eenheden te onderscheiden. Men onderscheidt bijvoorbeeld een “zwarte”, “bruine” of “grijze” laag of horizont.</p>
<p>Bepaal de kleur volgens het Munsell kleursysteem (code en benaming), samen met de vochtigheidstoestand van de bodem (zie § <a href="#bodemvochtigheid">4.3</a>). De Munsell code bevat drie componenten:</p>
<ul>
<li><p>Hue: dominante spectrale kleur of tint (houdt verband met de golflengte van het licht – <em>cfr.</em> regenboog);</p></li>
<li><p>Value: graad van donker (1) tot licht (8) of van zwart tot wit (hoeveelheid gereflecteerd licht);</p></li>
<li><p>Chroma: zuiverheid en sterkte (intensiteit) van spectrale kleur van bleek (1) tot helder (8).</p></li>
</ul>
<blockquote class="blockquote">
<p>Voorbeelden</p>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Kleurkaart:</th>
<th>10YR</th>
<th>GLEY 2<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></th>
<th>10Y – 5GY<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></th>
<th>WHITE<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Code</td>
<td>10YR 5/6</td>
<td>10BG 4/1</td>
<td>5GY 4/4</td>
<td>7.5YR 9.5/2</td>
</tr>
<tr class="even">
<td>Hue</td>
<td>10YR (geelrood)</td>
<td>10BG (blauwgroen)</td>
<td>5GY (groengeel)</td>
<td>7.5YR (geelrood)</td>
</tr>
<tr class="odd">
<td>Value</td>
<td>5</td>
<td>4</td>
<td>4</td>
<td>9.5</td>
</tr>
<tr class="even">
<td>Chroma</td>
<td>6</td>
<td>1</td>
<td>4</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Naam</td>
<td>Geelachtig bruin</td>
<td>Donker groenachtig grijs</td>
<td>Olijfgroen</td>
<td>Licht geelachtig roze</td>
</tr>
</tbody>
</table>
<p>Voorbeelden rapportering kleur:</p>
<p>Grijsachtig bruin 10YR 5/2 (vochtig) en lichtbruin grijs 10YR 6/2 (droog),</p>
<p>Donker grijsbruin tot grijsbruin 2.5Y 4,5/2 (vochtig) en lichtbruin grijs 2,5Y 6/2 (droog).</p>
</blockquote>
</section>
<section id="kleurvlekken" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="kleurvlekken"><span class="header-section-number">4.5</span> Kleurvlekken</h2>
<p>Vlekken kunnen allerlei vormen aannemen en zijn zones met een kleur die verschillend is van de dominante kleur van de bodemmatrix. Ze geven meestal aan dat de bodem afwisselend natte (reducerende) en droge (oxiderende) omstandigheden ondergaat. Andere vlekken kunnen het gevolg zijn van ongelijkmatige verwering van het moedermateriaal, klei (+ ijzer) migratie en accumulatie, selectieve afbraak door schimmels/bacteriën van organisch materiaal enz.</p>
<p>Beschrijf de vlekken in termen van kleur, aantal en contrast. Verder kan ook de grootte (in cm) en de duidelijkheid van de begrenzing (zie § <a href="#horizontbegrenzing">4.2.3</a>) van de vlekken worden bepaald. Bovendien kan de vorm, de positie of elk ander kenmerk worden beschreven.</p>
<section id="kleur" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="kleur"><span class="header-section-number">4.5.1</span> Kleur</h3>
<p>Bepaal de kleuren met de Munsell Soil Color Charts (zie § <a href="#bodemkleur">4.4</a>).</p>
<p>Als de kleur verandert na blootstelling aan de lucht (door oxidatie), bepaal dan de kleur zowel voor als na de oxidatie.</p>
</section>
<section id="aantal" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="aantal"><span class="header-section-number">4.5.2</span> Aantal</h3>
<p>Schat het percentage ingenomen door vlekken per aardkundige eenheid (zie <a href="#fig-04-14">fig.&nbsp;<span>4.14</span></a>) en verdeel onder in categorieën (tbl-04-05). Wanneer vlekken zo overheersen dat een onderscheid tussen matrix- en vlekkenkleur niet meer mogelijk is, beschrijf dan de overheersende kleuren (als bodemmatrixkleuren, zie § <a href="#bodemkleur">4.4</a>).</p>
<div id="tbl-04-05" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.5: Categorieën voor het schatten van het aantal vlekken</caption>
<thead>
<tr class="header">
<th>Categorie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zeer weinig (0-2%)</td>
</tr>
<tr class="even">
<td>Weinig (2-5%)</td>
</tr>
<tr class="odd">
<td>Vaak (5-15%)</td>
</tr>
<tr class="even">
<td>Veel (15-40%)</td>
</tr>
<tr class="odd">
<td>Zeer Veel (40%)</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="contrast" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="contrast"><span class="header-section-number">4.5.3</span> Contrast</h3>
<p>Beschrijf het kleurcontrast tussen vlekken en de matrix (<a href="#tbl-04-06">tabel&nbsp;<span>4.6</span></a>).</p>
<div id="tbl-04-06" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.6: De categorieën voor het omschrijven van de kleurcontrast van vlekken </caption>
<colgroup>
<col style="width: 22%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Omschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Onduidelijjk</td>
<td>De vlekken zijn enkel van dichtbij zichtbaar. Bodemkleuren van zowel de matrix als van de vlekken verschillen weinig van elkaar.</td>
</tr>
<tr class="even">
<td>Duidelijk</td>
<td>De vlekken zijn gemakkelijk te zien. Hue, chroma of value van de matrix is eenvoudig te onderscheiden van de vlekken.</td>
</tr>
<tr class="odd">
<td>Uitgesproken</td>
<td>De vlekken zijn opvallend. Hue, chroma en value, alleen of in combinatie, liggen verschillende eenheden uit elkaar</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="de-benaming-van-de-aardkundige-eenheid-horizontsymbolen" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="de-benaming-van-de-aardkundige-eenheid-horizontsymbolen"><span class="header-section-number">4.6</span> De benaming van de aardkundige eenheid (horizontsymbolen)</h2>
<section id="benaming" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="benaming"><span class="header-section-number">4.6.1</span> Hoofdhorizonten en -lagen (mastersymbolen)</h3>
<p>De hoofdletters H, O, A, E, B, C, L, R en T vertegenwoordigen de hoofdhorizonten of -lagen (<a href="#tbl-04-07">tabel&nbsp;<span>4.7</span></a>).</p>
<div id="tbl-04-07" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.7: De benaming van de hoofdhorizonten of -lagen.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th>Symbool</th>
<th>Beschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>H</td>
<td><p>Organische horizont gevormd onder langdurig waterverzadigde omstandigheden (veen). De H-horizonten worden naargelang de graad van ontbinding verder ingedeeld:</p>
<p>Hi (<em>fibric</em>), vrijwel intacte plantenresten, He (<em>mesic</em>), gedeeltelijk verteerd,</p>
<p>Ha (<em>sapric</em>), doorgedreven stadium van ontbinding.</p></td>
</tr>
<tr class="even">
<td>O</td>
<td><p>Organische horizont gevormd door accumulatie van plantenresten die op het bodemoppervlak zijn gevallen, maar niet in waterverzadigde omstandigheden.</p>
<p>Oi: bestaat uit niet tot weinig verteerd organisch materiaal, vooral strooisel zoals bladeren/naalden, twijgen, houtachtige materialen.</p>
<p>Oe: bestaat uit matig verteerd, vooral gefragmenteerd organisch materiaal waarvan de originele structuur nog te herkennen is.</p>
<p>Oa: bestaat uit vooral sterk verteerd organisch materiaal, humus; de originele structuur van het organisch materiaal is niet langer herkenbaar.</p></td>
</tr>
<tr class="odd">
<td>A</td>
<td>Minerale horizont aangerijkt met gehumificeerd organisch materiaal, gevormd aan of nabij het oppervlak.</td>
</tr>
<tr class="even">
<td>E</td>
<td>Minerale horizont waaruit klei en/of ijzer en/of aluminium zijn uitgeloogd (eluviatie); heeft meestal een lichtere kleur en/of lichtere textuur dan de boven- en onderliggende horizonten.</td>
</tr>
<tr class="odd">
<td>B</td>
<td><p>Minerale horizont meestal onder een A- of E-horizont, waarin bodemprocessen hebben plaatsgegrepen; de originele stratificatie of sedimentstructuur (i.e. geologische structuur) is ten minste grotendeels verdwenen. De belangrijkste bodemprocessen bij het transformeren van een C-horizont in een B-horizont zijn:</p>
<p>Kleurontwikkeling (verbruining), Structuurontwikkeling,</p>
<p>Ontkalking (uitloging van carbonaten),</p>
<p>Kleivorming door verwering van primaire bodemmineralen, Illuviatie (aanrijking) van ijzer, aluminium, klei, humus.</p></td>
</tr>
<tr class="even">
<td>C</td>
<td>Het moedermateriaal: een ongeconsolideerde minerale laag, niet of zeer weinig beïnvloed door bodemvormende processen, dus waar de geologische structuur domineert (eigenschappen kenmerkend voor de H-, O-, A-, E- of B-horizonten ontbreken).</td>
</tr>
<tr class="odd">
<td>L</td>
<td>Limnisch materiaal: sedimenten afgezet onder water, bestaande uit zowel organisch als mineraal bodemmateriaal. Limnisch materiaal is bijvoorbeeld afgezet door het neerslaan van organismen die in het water leefden zoals algen, diatomeeën, … of is afkomstig van onderwatervegetatie die later bewerkt werd door de waterfauna. Sedimentaire afzettingen van veen horen hierbij maar niet de afzettingen die bestaan uit <em>in situ</em> plantengroei (gebruik hiervoor de H).</td>
</tr>
<tr class="even">
<td>R</td>
<td>Weinig verweerd, of onverweerd, hard gesteente</td>
</tr>
<tr class="odd">
<td>T</td>
<td>Technisch harde materialen zoals asfalt, beton, funderingen, etc.</td>
</tr>
</tbody>
</table>
</div>
<section id="overgangshorizonten" class="level4" data-number="4.6.1.1">
<h4 data-number="4.6.1.1" class="anchored" data-anchor-id="overgangshorizonten"><span class="header-section-number">4.6.1.1</span> Overgangshorizonten</h4>
<p>Er zijn twee soorten overgangshorizonten (<a href="#fig-04-03">fig.&nbsp;<span>4.3</span></a>): horizonten met de eigenschappen van de boven- en de onderliggende horizont die geleidelijk in elkaar overgaan, en horizonten met eigenschappen van de twee horizonten maar van elkaar gescheiden (zowel horizontaal naast elkaar of elkaar snel afwisselend verticaal).</p>
<blockquote class="blockquote">
<p>Voorbeeld:</p>
<p>Op elkaar ontwikkeld: AB, BC,AE,… Gescheiden: A/B, B/C, C/R, E/B, E/Bt,…</p>
</blockquote>
<div id="fig-04-03" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image28.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.3: Bodem met geleidelijke overgang tussen de A en de E horizont (links), en een bodem met veel dunne E/Bt bandjes (rechts).</figcaption>
</figure>
</div>
</section>
</section>
<section id="bijkomende-kenmerken-van-een-horizontlaag-subordinate-symbolen" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="bijkomende-kenmerken-van-een-horizontlaag-subordinate-symbolen"><span class="header-section-number">4.6.2</span> Bijkomende kenmerken van een horizont/laag (subordinate symbolen)</h3>
<p>Bijkomende kenmerken binnen de hoofdhorizonten en lagen zijn gebaseerd op kenmerken die in het veld waarneembaar zijn. Kleine letters worden gebruikt als achtervoegsels om specifieke soorten hoofdhorizonten en lagen en andere kenmerken aan te duiden. De lijst met symbolen en termen wordt weergegeven in <a href="#tbl-04-08">tabel&nbsp;<span>4.8</span></a>:</p>
<div id="tbl-04-08" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.8: Bijkomende kenmerken voor de hoofdhorizonten en lagen</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 43%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Symbool</th>
<th>Beschrijving</th>
<th>Gebruik</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>a</td>
<td>Sterk verteerd organisch materiaal</td>
<td>H- en O-horizonten</td>
</tr>
<tr class="even">
<td>b</td>
<td>Begraven horizont of laag</td>
<td></td>
</tr>
<tr class="odd">
<td>β</td>
<td>Een biologisch zeer actieve horizont</td>
<td>Niet voor A-horizonten</td>
</tr>
<tr class="even">
<td>c</td>
<td>Concreties en/of nodules</td>
<td></td>
</tr>
<tr class="odd">
<td>d</td>
<td>Compacte horizont, wortelbeperkend</td>
<td></td>
</tr>
<tr class="even">
<td>e</td>
<td>Gedeeltelijk verteerd organisch materiaal</td>
<td>H- en O-horizonten</td>
</tr>
<tr class="odd">
<td>g</td>
<td>Oxido-reductie vlekken (Fe en/of Mn) veroorzaakt door een tijdelijk stagnerend watertafel</td>
<td></td>
</tr>
<tr class="even">
<td>h</td>
<td>Accumulatie van organische stof</td>
<td></td>
</tr>
<tr class="odd">
<td>i</td>
<td>Licht verteerd organisch materiaal</td>
<td>H- en O-horizonten</td>
</tr>
<tr class="even">
<td>j</td>
<td>Accumulatie van jarosiet</td>
<td></td>
</tr>
<tr class="odd">
<td>k</td>
<td>Accumulatie van secundaire kalk</td>
<td></td>
</tr>
<tr class="even">
<td>l</td>
<td>Oido-reductie vlekken (Fe en/of Mn) veroorzaakt door een fluctuerende grondwater tafel</td>
<td></td>
</tr>
<tr class="odd">
<td>m</td>
<td>Gecementeerde horizont</td>
<td>Vooral in B-horizont van Podzol</td>
</tr>
<tr class="even">
<td>m</td>
<td>Moeraskalk, mergel</td>
<td>L-horizont</td>
</tr>
<tr class="odd">
<td>p</td>
<td>Bewerkte horizont (ploeglaag…)</td>
<td>A-horizont (oppervlak of begraven)</td>
</tr>
<tr class="even">
<td>q</td>
<td>Accumulatie van silicium</td>
<td></td>
</tr>
<tr class="odd">
<td>r</td>
<td>Sterke reductie (permanente grondwatertafel)</td>
<td></td>
</tr>
<tr class="even">
<td>s</td>
<td>Illuviale accumulatie van sesquioxiden</td>
<td></td>
</tr>
<tr class="odd">
<td>t</td>
<td>Aanwezigheid van klei illuviatie</td>
<td>B-horizont</td>
</tr>
<tr class="even">
<td>u</td>
<td>Aanwezigheid van antropogeen materiaal</td>
<td></td>
</tr>
<tr class="odd">
<td>w</td>
<td>Kleur en/of structuur wegens bodemgenese</td>
<td>B-horizont</td>
</tr>
<tr class="even">
<td>x</td>
<td>Fragipan kenmerken (niet noodzakelijk een Bt)</td>
<td>o.a. Btx-horizont</td>
</tr>
<tr class="odd">
<td>y</td>
<td>Accumulatie van gips</td>
<td></td>
</tr>
<tr class="even">
<td>z</td>
<td>Accumulatie van zouten die meer oplosbaar zijn dan gips</td>
<td></td>
</tr>
<tr class="odd">
<td>zo</td>
<td>Zoögenetisch (van dierlijke oorsprong: meso of macrofauna)</td>
<td>Enkel voor H-, O- en A-horizonten Te plaatsen voor het hoofdsymbool</td>
</tr>
<tr class="even">
<td>noz</td>
<td>Niet zoögenetisch (geen dierlijke activiteit, wel aanwezigheid van schimmels).</td>
<td>Enkel voor H-, O- en A-horizonten Te plaatsen voor het hoofdsymbool</td>
</tr>
<tr class="odd">
<td>@</td>
<td>Sporen van cryoturbatie</td>
<td></td>
</tr>
<tr class="even">
<td>^</td>
<td>Antropogeen (mechanisch) aangevoerd materiaal</td>
<td>te plaatsen voor het hoofdsymbool</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="vertikale-onderverdelingen" class="level3" data-number="4.6.3">
<h3 data-number="4.6.3" class="anchored" data-anchor-id="vertikale-onderverdelingen"><span class="header-section-number">4.6.3</span> Vertikale onderverdelingen</h3>
<p>Een horizont of laag kunnen we verder onderverdelen en duiden we aan met een combinatie van lettersymbolen gevolgd door een cijfer. De cijfers worden gebruikt om horizonten met dezelfde symbolen van elkaar te kunnen scheiden.</p>
<blockquote class="blockquote">
<p>Voorbeeld:</p>
<ul>
<li>C1-C2-C3</li>
<li>C1-C2-Cg1-Cg2</li>
<li>C-Cg1-Cg2</li>
<li>Bt1-Bt2-Ck1-Ck2</li>
</ul>
</blockquote>
<section id="lithologische-discontinuïteit" class="level4" data-number="4.6.3.1">
<h4 data-number="4.6.3.1" class="anchored" data-anchor-id="lithologische-discontinuïteit"><span class="header-section-number">4.6.3.1</span> Lithologische discontinuïteit</h4>
<p>Een lithologische discontinuïteit is een significante verandering in het bodemmateriaal, bijvoorbeeld tussen het moedermateriaal en een onderliggend substraat (zie § <a href="03_bodemvorming.html#substraat">3.2</a>). Dit kan zich weerspiegelen in een verandering in de korrelgroottesamenstelling en/of de mineralogie. Duid het verschil in substraat aan met een cijfer voor het hoofdsymbool. Bij het bovenste moedermateriaal dien je echter geen “1” te vermelden (<a href="#fig-04-04">fig.&nbsp;<span>4.4</span></a>).</p>
<div id="fig-04-04" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image39.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.4: Voorbeeld van een bodem die bestaat uit 4 verschillende moedermaterialen of 1 moedermateriaal en 3 substraten.</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="antropogeen-mechanisch-aangevoerd-materiaal" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="antropogeen-mechanisch-aangevoerd-materiaal"><span class="header-section-number">4.7</span> Antropogeen (mechanisch) aangevoerd materiaal</h2>
<p>Antropogeen (mechanisch) aangevoerd materiaal (meestal sinds de industriële periode) wordt geïdentificeerd aan de hand van:</p>
<ul>
<li><p>De manier van afzetting (abrupte grenzen, verdichting…),</p></li>
<li><p>De aanwezigheid al dan niet van artefacten,</p></li>
<li><p>De beperkte afwezigheid van bodemvormende kenmerken,</p></li>
<li><p>Afwezigheid van natuurlijk transport (bijvoorbeeld door wind, water…).</p></li>
</ul>
<p>Aardkundige eenheden ontwikkeld in antropogeen aangevoerd materiaal worden beschreven met hetzelfde detailniveau als horizonten ontwikkeld in het moedermateriaal. Het voorvoegsel ^ wordt gebruikt om door mensen vervoerd materiaal aan te duiden (Soil Survey Staff, 2014; Delbecque <em>et al.</em>, 2022), terwijl het gebruik van bijkomende symbolen (<a href="#tbl-04-09">tabel&nbsp;<span>4.9</span></a>) dienen om eigenschappen aan te duiden die van het antropogeen aangevoerd materiaal zelf zijn geërfd. Zie ook <a href="#fig-04-05">fig.&nbsp;<span>4.5</span></a> en <a href="#fig-04-06">fig.&nbsp;<span>4.6</span></a>.</p>
<div id="tbl-04-09" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.9: Voorbeelden van horizontbenamingen voor antropogeen (mechanisch) aangevoerd materiaal.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th>Symbool</th>
<th>Beschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>^T</td>
<td>Technisch hard materiaal, aangevoerd (bv tegels, betonlaag, glas, asfalt, …)</td>
</tr>
<tr class="even">
<td>^A</td>
<td>Oppervlaktehorizont ontwikkeld in antropogeen aangevoerd materiaal</td>
</tr>
<tr class="odd">
<td>^Ah</td>
<td>Oppervlaktehorizont ontwikkeld in antropogeen aangevoerd materiaal aangerijkt met organisch materiaal</td>
</tr>
<tr class="even">
<td>^Ab</td>
<td>Begraven oppervlaktehorizont van antropogeen aangevoerd mineraal materiaal</td>
</tr>
<tr class="odd">
<td>^Bw</td>
<td>Aangevoerd mineraal bodemmateriaal. De kleur- of structuurontwikkeling (‘w’) is een kenmerk overgenomen van het aangevoerd materiaal of kan in situ gevormd zijn</td>
</tr>
<tr class="even">
<td>^E</td>
<td>Aangevoerd mineraal materiaal van een oorspronkelijke uitlogingshorizont</td>
</tr>
<tr class="odd">
<td>^C</td>
<td>Mineraal materiaal, waar sinds de antropogene afzetting geen bodemvorming in opgetreden is, dus waarin nog geen nieuwe bodemstructuur of verkleuring voorkomt die erop wijst dat verwering heeft plaats gevonden</td>
</tr>
<tr class="even">
<td>^Ch</td>
<td>Aangevoerd mineraal materiaal rijk aan organisch materiaal, waar sinds de antropogene afzetting geen bodemvorming in opgetreden is</td>
</tr>
<tr class="odd">
<td>^Cu</td>
<td>Aangevoerd mineraal materiaal gedomineerd door afval van menselijke nederzettingen en/of industriële residuen (slakkenhopen, bagger, klinkers, as, puin, etc.)</td>
</tr>
</tbody>
</table>
</div>
<div id="fig-04-05" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image46.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.5: Voorbeelden van bodems met antropogeen (mechanisch) aangevoerd materiaal. Links: Een goed tot matig-goed gedraineerde lemig-zandbodem ontwikkeld in recent aangevoerd materiaal boven een slecht gedraineerde leembodem met een dikke humus A horizont (bodemtype Afe). ^Ah: in-situ horizont met organisch materiaal geaccumuleerd. ^Ap: sporen van bewerking, bevat stenen, asfalt en bouwpuin. Rechts: Onderaan een slechte gedraineerde leembodem met een duidelijke Ah horizont, die deels afgetopt is geweest. Bovenaan 170 cm aangevoerd grond. ^Au: lemig zand met zeer grove stenen. ^Cu1: mengeling grind, asfalt en grove stenen. ^Cu2: glauconiethoudend zand, met bouwpuin met grove stenen. Boven de ^Au-horizont ligt voor de aanleg van de profielput uitgegraven materiaal (Foto’s: Stefaan Dondeyne).</figcaption>
</figure>
</div>
<p><br></p>
<div id="fig-04-06" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image47.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.6: Voorbeeld van bodem met antropogeen aangevoerd materiaal. Begraven bodemprofiel (2Ap-2Bw-2CBg) bestaande uit restanten van een muur (T), met daaronder aangevoerd grofzand (C horizont), zandig aangevoerd materiaal dat initieel rijk was aan organisch materiaal (^Ch), en een laag rijk aan bouwpuin resten (^Cu) (Foto: Stefaan Dondeyne).</figcaption>
</figure>
</div>
<section id="textuur" class="level3" data-number="4.7.1">
<h3 data-number="4.7.1" class="anchored" data-anchor-id="textuur"><span class="header-section-number">4.7.1</span> Textuur</h3>
<p>In de bodemkunde verwijst “<strong>textuur</strong>” naar de verhouding, uitgedrukt in een massapercentage, van drie <strong>minerale</strong> korrelgroottefracties klei, leem en zand in het fijne bodemmateriaal (fractie 0 – 2 mm). Naargelang de verhouding van klei, leem en zand kan men verschillende textuurklassen onderscheiden (<a href="#tbl-04-10">tabel&nbsp;<span>4.10</span></a>; <a href="#fig-04-07">fig.&nbsp;<span>4.7</span></a> en <a href="#fig-04-08">fig.&nbsp;<span>4.8</span></a>).</p>
<div id="tbl-04-10" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.10: De textuurklassen (categorieën) en hun benaming.</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Benaming</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Z</td>
<td>Zand</td>
</tr>
<tr class="even">
<td>S</td>
<td>Lemig zand</td>
</tr>
<tr class="odd">
<td>P</td>
<td>Licht zandleem</td>
</tr>
<tr class="even">
<td>L</td>
<td>Zandleem</td>
</tr>
<tr class="odd">
<td>A</td>
<td>Leem</td>
</tr>
<tr class="even">
<td>E</td>
<td>Klei</td>
</tr>
<tr class="odd">
<td>U</td>
<td>Zware klei</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<blockquote class="blockquote">
<p>Voorbeeld:</p>
<p>10% klei, 60% leem en 30% zand (het totaal is steeds 100), textuurklasse ‘L – Zandleem’</p>
</blockquote>
<p><br></p>
<p>De textuur kan met een handige veldtest (<a href="#fig-04-07">fig.&nbsp;<span>4.7</span></a>) worden bepaald en aangeduid volgens de klasse-indeling en klassegrenzen van de textuurdriehoek van de Belgische bodemkartering (figuur 13). Opletten, bij een hoger gehalte aan organisch materiaal kan in het veld de textuur kleirijker aanvoelen.</p>
<div id="fig-04-07" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image48.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.7: Bepalen van de textuur in het veld (door Sylvia Mazereel en naar Petit &amp; Heyninck 2019)</figcaption>
</figure>
</div>
<p><br></p>
<div id="fig-04-08" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image54.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.8: De fijne minerale bodemfractie (&lt; 2mm) en de textuurklassen gebruikt bij de Belgische bodemkartering. De streepjeslijnen tonen een voorbeeld bestaande uit 10% klei, 30% zand en 60% leem. Dit voorbeeld komt terecht in de textuurklasse L - Zandleem.</figcaption>
</figure>
</div>
</section>
<section id="aanwezigheid-van-kleihuidjes" class="level3" data-number="4.7.2">
<h3 data-number="4.7.2" class="anchored" data-anchor-id="aanwezigheid-van-kleihuidjes"><span class="header-section-number">4.7.2</span> Aanwezigheid van kleihuidjes</h3>
<p>Onder bepaalde omstandigheden zal klei migreren in de bodem. Het herkennen van dit bodemproces tijdens het veldwerk is belangrijk (ouderdom, pH-regime, …). Gebruik een handlens om kleihuidjes op structuuroppervlakken of in poriën te kunnen vaststellen (zie ook <a href="#fig-04-17">fig.&nbsp;<span>4.17</span></a>). Noteer ook of het gaat om klei, klei + humus of klei + ijzer huidjes.</p>
<ul>
<li><p>Zie ook <a href="#tbl-04-08">tabel&nbsp;<span>4.8</span></a>: voor het toepassen van het bodemhorizontsymbool ‘t’.</p></li>
<li><p>Zie ook <a href="05_classificatie.html#tbl-05-04">tabel&nbsp;<span>5.3</span></a>: voor het toepassen van de Belgische bodemkaartsymbolen ‘a’ en ‘c’.</p></li>
</ul>
</section>
</section>
<section id="grove-fragmenten" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="grove-fragmenten"><span class="header-section-number">4.8</span> Grove fragmenten</h2>
<p>‘Grove fragmenten’ in de bodem hebben een diameter groter dan 2 mm (voor oppervlaktestenen zie § <a href="#Oppervlaktestenen">4.1</a>. Het kan gaan om grind, gesteentefragmenten, bakstenen, etc. maar niet om materiaal van organische oorsprong zoals wortels, takken etc.</p>
<p>Verschillende eigenschappen kunnen worden beschreven: oorsprong, frequentie (<a href="#tbl-04-11">tabel&nbsp;<span>4.11</span></a>), grootte (<a href="#tbl-04-12">tabel&nbsp;<span>4.12</span></a>), vorm (<a href="#tbl-04-13">tabel&nbsp;<span>4.13</span></a>), staat van verwering en aard van de fragmenten.</p>
<p><a href="#fig-04-09">fig.&nbsp;<span>4.9</span></a> kan helpen bij de visuele schatting van het volume aan grove fragmenten zichtbaar op de bodemwand (Let op: er is een algemene neiging om de hoeveelheden te overschatten). Gebruik hiervoor de categorieën uit <a href="#tbl-04-11">tabel&nbsp;<span>4.11</span></a>.</p>
<div id="tbl-04-11" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.11: De categorieën voor de frequentie grove fragmenten.</caption>
<thead>
<tr class="header">
<th>Categorie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geen (0 %)</td>
</tr>
<tr class="even">
<td>Zeer weinig (0-2 %)</td>
</tr>
<tr class="odd">
<td>Weinig (2-5 %)</td>
</tr>
<tr class="even">
<td>Vaak (5-15 %)</td>
</tr>
<tr class="odd">
<td>Veel (15-40 %)</td>
</tr>
<tr class="even">
<td>Zeer veel (40 %)</td>
</tr>
</tbody>
</table>
</div>
<div id="fig-04-09" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image55.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.9: Referentie voor het visueel schatten van het oppervlakte percentage aan vlekken, of van het volume percentage aan grove fragmenten (of andere elementen)</figcaption>
</figure>
</div>
<div id="tbl-04-12" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.12: Categorieën voor de grootte van de grove fragmenten.</caption>
<colgroup>
<col style="width: 51%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Grootte</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fijn (0,2–0,6 cm) | G</td>
<td>rind</td>
</tr>
<tr class="even">
<td>Gemiddeld (0,6–2 cm) | G</td>
<td>rind</td>
</tr>
<tr class="odd">
<td>Grof (2–6 cm) | G</td>
<td>rind</td>
</tr>
<tr class="even">
<td>Zeer grof (\6 cm) | St</td>
<td>enen en rotsen</td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-04-13" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.13: Categorieën voor de dominante vorm van de fragmenten.</caption>
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Plat</td>
</tr>
<tr class="even">
<td>Hoekig</td>
</tr>
<tr class="odd">
<td>Gedeeltelijk afgerond</td>
</tr>
<tr class="even">
<td>Afgerond</td>
</tr>
</tbody>
</table>
</div>
<p>Bij gesteentefragmenten kan je de staat van verwering beschrijven (<a href="#tbl-04-14">tabel&nbsp;<span>4.14</span></a>).</p>
<div id="tbl-04-14" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.14: De categorieën voor de staat van verwering van de grove fragmenten te omschrijven.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Omschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vers of licht verweerd</td>
<td>fragmenten vertonen weinig of geen sporen van verwering</td>
</tr>
<tr class="even">
<td>Verweerd</td>
<td>gedeeltelijke verwering wordt aangegeven door verkleuring en verlies van kristalvorm in het buitenste deel van de fragmenten, terwijl de kernen relatief vers blijven; fragmenten hebben weinig van hun oorspronkelijke sterkte verloren</td>
</tr>
<tr class="odd">
<td>Sterk verweerd</td>
<td>alle behalve de meest resistente mineralen zijn sterk verkleurd en veranderd; de fragmenten hebben de neiging onder (hand)druk uiteen te vallen</td>
</tr>
</tbody>
</table>
</div>
<section id="type-fragmenten" class="level3" data-number="4.8.1">
<h3 data-number="4.8.1" class="anchored" data-anchor-id="type-fragmenten"><span class="header-section-number">4.8.1</span> Type fragmenten</h3>
<p>De grove fractie wordt in antropogeen materiaal en natuurlijke gesteentefragmenten onderverdeeld.</p>
<blockquote class="blockquote">
<p>Voorbeeld:</p>
<p><u>Antropogeen</u>: Baksteen; steenkool; houtskool; aardewerk; mortel/pleister; <u>Natuurlijk</u>: keien; schelpen; natuurlijk voorkomende stenen;</p>
</blockquote>
</section>
<section id="distributieverspreiding-van-de-grove-fractie-in-het-profiel" class="level3" data-number="4.8.2">
<h3 data-number="4.8.2" class="anchored" data-anchor-id="distributieverspreiding-van-de-grove-fractie-in-het-profiel"><span class="header-section-number">4.8.2</span> Distributie/verspreiding van de grove fractie in het profiel</h3>
<p>Bestudeer de verspreiding van zowel de natuurlijke gesteenten als van het antropogene materiaal.</p>
<blockquote class="blockquote">
<p>Voorbeeld:</p>
<ul>
<li>Willekeurig</li>
<li>Geconcentreerd</li>
<li>In een laag</li>
<li>In een spoor</li>
</ul>
</blockquote>
</section>
<section id="cappings-en-pendants" class="level3" data-number="4.8.3">
<h3 data-number="4.8.3" class="anchored" data-anchor-id="cappings-en-pendants"><span class="header-section-number">4.8.3</span> Cappings en pendants</h3>
<section id="cappings" class="level4" data-number="4.8.3.1">
<h4 data-number="4.8.3.1" class="anchored" data-anchor-id="cappings"><span class="header-section-number">4.8.3.1</span> Cappings</h4>
<p>Gesteentefragmenten in de bodem kunnen, onder invloed van vries/dooi cycli, aan hun bovenkant een sterke adhesie vertonen met de bodemmatrix waarin ze zich bevinden. Aan de onderkant van het gesteente kleeft er geen of weinig matrixmateriaal aan het gesteente. De stenen in kwestie zijn als het ware voorzien van een soort ‘sedimentkapje’ (<a href="#fig-04-10">fig.&nbsp;<span>4.10</span></a>).</p>
<div id="fig-04-10" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image56.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.10: Voorbeeld van capping op gesteenten. (copyright en Foto: Roger Langohr).</figcaption>
</figure>
</div>
<p>Artefacten die dergelijk kenmerk bezitten wijzen op een periode met belangrijke vries/dooi in de bodem. De laatste periode is tijdens de Jonge Dryas. Het is belangrijk om artefacten van vóór en na de Jonge Dryas te onderscheiden vermits het belangrijke informatie vormt over de diverse perioden van het Finaal-Paleolithicum (±13.000-9.600 BP).</p>
<p>Omdat de capping niet bij elk fragment even sterk is ontwikkeld, bekijk je er best een aantal terwijl je er goed op let ze in dezelfde positie te houden, zoals ze in de bodem voorkomen. Het is belangrijk de artefacten met capping niet schoon te maken, zo niet gaat deze essentiële bodemkundige informatie verloren!</p>
<p>Normaal bevindt de capping zich aan de bovenzijde van artefacten; indien dit niet het geval is, wijst dit op een latere verstoring (cryoturbatie, bioturbatie…).</p>
</section>
<section id="pendants" class="level4" data-number="4.8.3.2">
<h4 data-number="4.8.3.2" class="anchored" data-anchor-id="pendants"><span class="header-section-number">4.8.3.2</span> Pendants</h4>
<p>Een pendant is een laminaire accumulatie van bodemvormend materiaal, bijvoorbeeld calciumcarbonaat of silica, dat accumuleert onderaan de grove fractie (grind, stenen, …) die aanwezig is in de bodem (<a href="#fig-04-11">fig.&nbsp;<span>4.11</span></a>).</p>
<div id="fig-04-11" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image57.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.11: Voorbeeld van pendants op gesteenten (copyright en Foto’s: Roger Langohr).</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="bodemstructuur" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="bodemstructuur"><span class="header-section-number">4.9</span> Bodemstructuur</h2>
<p>Bodemstructuur gaat over de natuurlijke aggregaten die door barsten of poriën van elkaar zijn gescheiden. Bodemstructuur wordt aan de hand van de dominante vorm, de afmetingen, de graad en oorsprong van ontwikkeling van de aggregaten (<a href="#fig-04-12">fig.&nbsp;<span>4.12</span></a>) beschreven. Opletten, de beschrijving van kruimelige structuur volgt Ameryckx <em>et al.</em>, 1995 en is conform de Belgische bodemkartering en de Vlaamse bodemdatabanken. Deze definitie is anders dan die van FAO 2006.</p>
<section id="types-van-bodemstructuur" class="level4" data-number="4.9.0.1">
<h4 data-number="4.9.0.1" class="anchored" data-anchor-id="types-van-bodemstructuur"><span class="header-section-number">4.9.0.1</span> Types van bodemstructuur</h4>
<p>Beschrijf de types (categorieën) van bodemstructuren volgens <a href="#tbl-04-15">tabel&nbsp;<span>4.15</span></a>.</p>
<div id="tbl-04-15" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.15: De types van bodemstructuur (categorieën) en hun omschrijving.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Omschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kruimelig</td>
<td>Sferisch, zeer poreus, eenheden die niet in elkaar passen. De kruimelstructuur kent een goede lucht-water verhouding. Een goed ontwikkelde kruimelstructuur wordt vaak met regenwormuitwerpselen, molshopen en sterke doorworteling in graszoden geassocieerd, maar ook in goed beheerde akkerlanden met organische mest en groenbedekkers kan de ploeglaag een goed ontwikkelde kruimelstructuur vertonen</td>
</tr>
<tr class="even">
<td>Granulair</td>
<td>Sferisch, weinig poreus, aggregaten zijn gebogen of onregelmatig van vorm. Naast elkaar liggende aggregaten passen niet in elkaar. Onder andere gevormd door vries/dooi in kleirijke bodems en een sterke biologische activiteit aan het bodemoppervlak</td>
</tr>
<tr class="odd">
<td>Platig</td>
<td>Plaat-, blad- of lensvormen, liggen meestal evenwijdig aan het bodemoppervlak. De dikte varieert van amper een millimeter (blad) tot enkele centimeters. Meestal gevormd ten gevolge van compactie (betreding of berijding bijvoorbeeld) of door vries/dooi cycli en komt in dat geval eerder voor in een compacte horizont of laag (bv.: Bt-horizont…). Opgelet: dit mag niet verward worden met stratificatie of gelaagdheid (zie hieronder)</td>
</tr>
<tr class="even">
<td>Hoekig- blokkig</td>
<td>Kubusvorm, bijna equidimensionaal, met relatief scherpe hoeken en vlakke oppervlakken die goed aansluiten met de omliggende blokeenheden, doorgaans enkele cm in diameter. Gevormd door alternerend zwellen en krimpen ten gevolge van wisselingen in de bodemvochtigheid, vandaar een sterk verband met de hoeveelheid klei: hoe meer klei, hoe beter ontwikkeld</td>
</tr>
<tr class="odd">
<td>Subhoekig- blokkig</td>
<td>Zoals voorgaande maar met afgeronde oppervlakken, genese zoals voorgaande maar met een zekere invloed van biologische activiteit, vandaar de meer afgeronde morfologie</td>
</tr>
<tr class="even">
<td>Prismatisch</td>
<td>De afmetingen zijn groter in verticale dan in horizontale richting, vormt polygonen in horizontaal vlak. De prisma’s kunnen meerdere decimeters in diameter zijn, de vorming ervan is vooral te wijten aan alternerend zwellen en krimpen ten gevolge van wisselingen in de bodemvochtigheid, krimp alleen komt voor bij uitdroging van waterverzadigde bodems (frequent in archeologische structuren), of bij permafrost (fragipan horizont)</td>
</tr>
<tr class="odd">
<td>Loskorrelig</td>
<td>Loskorrelig in geval van zand (bv. duinzanden) (Structuurloos)</td>
</tr>
<tr class="even">
<td>Massief</td>
<td>Massief kan voorkomen bij fijnere bodemtexturen. Er is geen organisatie van de bodemdeeltjes in aggregaten (recent alluvium en colluvium, recente stortlaag) (Structuurloos)</td>
</tr>
<tr class="odd">
<td>Gelaagd</td>
<td>De bodem is uit sedimentaire lagen opgebouwd (Structuurloos)</td>
</tr>
</tbody>
</table>
</div>
<div id="fig-04-12" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image58.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.12: Types bodemstructuren (door Sylvia Mazereel en vereenvoudigd volgens FAO, 2006)</figcaption>
</figure>
</div>
</section>
<section id="de-afmetingen" class="level4" data-number="4.9.0.2">
<h4 data-number="4.9.0.2" class="anchored" data-anchor-id="de-afmetingen"><span class="header-section-number">4.9.0.2</span> De afmetingen</h4>
<p>De afmetingen van de bodemstructuureenheden kunnen met grootteklassen worden beschreven (<a href="#tbl-04-16">tabel&nbsp;<span>4.16</span></a>).</p>
<p><br></p>
<blockquote class="blockquote">
<p>Voorbeeld</p>
<p>Zeer grof of dik prismatisch (300-400 mm)</p>
</blockquote>
<p><br></p>
<div id="tbl-04-16" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.16: Grootteklassen en afmetingen in mm in functie van het type bodemstructuur</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 26%">
<col style="width: 19%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Kruimelig/blokkig (mm)</th>
<th>Prismatisch (mm)</th>
<th>Platig/granulair (mm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zeer fijn of dun</td>
<td>0-5</td>
<td>0-10</td>
<td>0-1</td>
</tr>
<tr class="even">
<td>Fijn of dun</td>
<td>&gt;5-10</td>
<td>&gt;10-20</td>
<td>&gt;1-2</td>
</tr>
<tr class="odd">
<td>Medium</td>
<td>&gt;10-20</td>
<td>&gt;20-50</td>
<td>&gt;2-5</td>
</tr>
<tr class="even">
<td>Grof of dik</td>
<td>&gt;20-50</td>
<td>&gt;50-100</td>
<td>&gt;5-10</td>
</tr>
<tr class="odd">
<td>Zeer grof of dik</td>
<td>&gt;50</td>
<td>&gt;100-500</td>
<td>&gt;10</td>
</tr>
<tr class="even">
<td>Extreem grof</td>
<td><ul>
<li></li>
</ul></td>
<td>&gt;500</td>
<td><ul>
<li></li>
</ul></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="de-graad-van-structuurontwikkeling" class="level4" data-number="4.9.0.3">
<h4 data-number="4.9.0.3" class="anchored" data-anchor-id="de-graad-van-structuurontwikkeling"><span class="header-section-number">4.9.0.3</span> De graad van structuurontwikkeling</h4>
<p>De ontwikkeling van de bodemstructuur is afhankelijk van de vochtigheidsgraad: hoe droger, hoe gemakkelijker je de aggregaten, door het krimpproces bij uitdrogen, kan herkennen.</p>
<p>Als de structuur niet goed ontwikkeld is, kan het moeilijk zijn om de mate van ontwikkeling van de structuur in te schatten, vooral als de bodem vochtig is. Kijk of de aggregaten aan alle kanten of slechts aan enkele zijden goed zijn afgebakend en hoe gemakkelijk de aggregaten van elkaar te scheiden zijn. De graad van ontwikkeling van structuur wordt gedefinieerd in <a href="#tbl-04-17">tabel&nbsp;<span>4.17</span></a>.</p>
<div id="tbl-04-17" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.17: Categorieën voor de graad van de structuurontwikkeling.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Beschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geen</td>
<td>Structuurloos, zoals voor loskorrelig, massief of gelaagd (<a href="#fig-04-12">fig.&nbsp;<span>4.12</span></a>)</td>
</tr>
<tr class="even">
<td>Zwak</td>
<td>Aggregaten zijn nauwelijks waarneembaar, er is slechts een zwakke schikking van natuurlijke oppervlakken. Bij een zachte verstoring breekt het bodemmateriaal in een mengeling van weinig volledige aggregaten, veel gebroken aggregaten en veel materiaal zonder aggregaatvlakken.</td>
</tr>
<tr class="odd">
<td>Matig</td>
<td>Aggregaten zijn in het profiel waarneembaar en er is een duidelijke schikking van structuurvlakken. Bij verstoring breekt het bodemmateriaal in een mengeling van vele volledige aggregaten, sommige gebroken aggregaten en weinig materiaal zonder aggregaatvlakken. De oppervlakken vertonen over het algemeen duidelijke verschillen met de binnenkant van de aggregaten.</td>
</tr>
<tr class="even">
<td>Sterk</td>
<td>Aggregaten zijn duidelijk waarneembaar en er is een uitgesproken schikking van de structuurvlakken. Bij verstoring valt het bodemmateriaal vooral uiteen in volledige aggregaten. De structuurvlakken van de aggregaten en de binnenkant van de aggregaten verschillen sterk van kleur</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="samengestelde-structuur" class="level4" data-number="4.9.0.4">
<h4 data-number="4.9.0.4" class="anchored" data-anchor-id="samengestelde-structuur"><span class="header-section-number">4.9.0.4</span> Samengestelde structuur</h4>
<p>De aanwezigheid van meer dan één structuurtype in een bodemhorizont komt geregeld voor. In zo’n geval worden beide structuurtypes volgens vorm, afmeting en graad van ontwikkeling beschreven.</p>
<blockquote class="blockquote">
<p>Voorbeeld</p>
<p>Sterk prismatisch, tot 30 cm diameter, brekend in matig hoekige blokstructuur van 2-4 cm diameter (<a href="#fig-04-13">fig.&nbsp;<span>4.13</span></a>).</p>
</blockquote>
<div id="fig-04-13" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image71.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.13: Voorbeeld van een bodem met aan de bovenkant een prismatisch structuur die uiteen valt in hoekig-blokkig. Het profiel toont een Grondwaterpodzol op dekzanden afgedekt door 40-45 cm polderklei. (copyright en foto: Jari Mikkelsen).</figcaption>
</figure>
</div>
</section>
<section id="cementatie" class="level3" data-number="4.9.1">
<h3 data-number="4.9.1" class="anchored" data-anchor-id="cementatie"><span class="header-section-number">4.9.1</span> Cementatie</h3>
<p>De belangrijkste cementerende stoffen zijn:</p>
<ul>
<li><p>Silicium</p></li>
<li><p>Kalk</p></li>
<li><p>IJzer</p></li>
<li><p>Mangaan</p></li>
<li><p>Humus.</p></li>
</ul>
<p>Gecementeerde horizonten of bodemlagen hebben meestal een grove korrelgrootte (zand, grind) (<a href="#fig-04-14">fig.&nbsp;<span>4.14</span></a>, links en <a href="#fig-04-14">fig.&nbsp;<span>4.14</span></a>, rechts) omdat er slechts een kleine hoeveelheid cement nodig is om de contactvlakken van grote korrels aan elkaar te doen kitten. De humus/ijzer-aanrijkingshorizont van podzolen kan soms gecementeerd zijn. Wortels kunnen niet door een gecementeerde horizont groeien tenzij langs barsten. Een gecementeerd bodemfragment valt <u>niet</u> uit elkaar wanneer een luchtdroog fragment gedurende 1 uur in water wordt ondergedompeld. Voor de graad van cementatie zie <a href="#tbl-04-18">tabel&nbsp;<span>4.18</span></a>.</p>
<div id="fig-04-14" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image72.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.14: Voorbeelden van cementatie van de bodem. <u>Links</u>: grindpakket gecementeerd door kalk (rode pijl). De cementatie wordt opgebroken/ opgelost in het Holoceen onder impuls van de biologische activiteit (witte pijl). Parijs-Louvre Jardins du Carrousel, laagterras van de Seine, (copyright Fouilles du Carrousel). <u>Rechts</u>: IJzeroxidecementatie van het bodemprofiel tussen 30 en 60 cm, hier gebruikt als bouwmateriaal in een weg uit de Romeinse periode in Grobbendonk [Foto: Stefaan Dondeyne].</figcaption>
</figure>
</div>
<div id="tbl-04-18" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.18: De graad van cementatie.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Omschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zwak</td>
<td>Gecementeerde massa is broos en hard, maar kan je tussen de vingers breken</td>
</tr>
<tr class="even">
<td>Matig</td>
<td>Gecementeerde massa kan je niet tussen de vingers, maar wel met de handen breken</td>
</tr>
<tr class="odd">
<td>Sterk</td>
<td>Gecementeerde massa kan je niet met de handen breken</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="compactie" class="level3" data-number="4.9.2">
<h3 data-number="4.9.2" class="anchored" data-anchor-id="compactie"><span class="header-section-number">4.9.2</span> Compactie</h3>
<p>Compacte bodemhorizonten of lagen komen onder andere voor in akkers (ploegzool) bewerkt onder ongunstige omstandigheden, zones van betreding rond huizen, bij bosontginning, wegen en paden, drinkplaatsen van vee, recreatie. Natuurlijke processen zoals vries/dooi cycli en permafrost kunnen de bodem ook sterk compact maken.</p>
<p><strong>Let op</strong>: gecompacteerde bodemhorizonten of lagen zijn niet noodzakelijk gecementeerd. Compactheid is een ander bodemkenmerk. Een compact, niet gecementeerd bodemfragment valt uit elkaar als het luchtdroog in water wordt ondergedompeld.</p>
</section>
<section id="levende-wortels" class="level3" data-number="4.9.3">
<h3 data-number="4.9.3" class="anchored" data-anchor-id="levende-wortels"><span class="header-section-number">4.9.3</span> Levende wortels</h3>
<p>Aanwezigheid (<strong>ja/neen</strong>) van levende wortels, hun grootte en hoeveelheid kan een belangrijke informatiebron zijn. Als er in het profiel een plotselinge verandering in de hoeveelheid en/of de grootte van de wortels voorkomt, is het belangrijk om uit te leggen waarom. Mogelijke wortelbeperkende factoren zijn: verdichting, cementatie, discontinu poriënsysteem, verandering in textuur enz. Soms kan het handig zijn om extra informatie te noteren, zoals een abrupte verandering in de wortel-oriëntatie.</p>
<section id="aantal-1" class="level4" data-number="4.9.3.1">
<h4 data-number="4.9.3.1" class="anchored" data-anchor-id="aantal-1"><span class="header-section-number">4.9.3.1</span> Aantal</h4>
<p>Het aantal levende wortels wordt per vierkante decimeter op een verticaal bodemoppervlak ingeschat. Maak een inschatting van het aantal wortels per grootteklasse (<a href="#tbl-04-19">tabel&nbsp;<span>4.19</span></a>).</p>
<div id="tbl-04-19" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.19: De grootteklassen en de afmetingen in functie van de frequentie van wortels per dm².</caption>
<colgroup>
<col style="width: 23%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th><p>Grootteklasse</p>
<p>Aantal:</p></th>
<th><p>Zeer fijn</p>
<p>&lt;0,5 mm</p></th>
<th><p>Fijn</p>
<p>0,5-2 mm</p></th>
<th><p>Medium</p>
<p>&gt; 2-5 mm</p></th>
<th><p>Grof</p>
<p>&gt;5 mm</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geen</td>
<td><ul>
<li></li>
</ul></td>
<td><ul>
<li></li>
</ul></td>
<td><ul>
<li></li>
</ul></td>
<td><ul>
<li></li>
</ul></td>
</tr>
<tr class="even">
<td>Zeer weinig</td>
<td>1-20</td>
<td>1-20</td>
<td>1-2</td>
<td>1-2</td>
</tr>
<tr class="odd">
<td>Weinig</td>
<td>21-50</td>
<td>21-50</td>
<td>3-5</td>
<td>3-5</td>
</tr>
<tr class="even">
<td>Matig veel</td>
<td>5 1-200</td>
<td>5 1-200</td>
<td>6-20</td>
<td>6-20</td>
</tr>
<tr class="odd">
<td>Veel</td>
<td>&gt;200</td>
<td>&gt;200</td>
<td>&gt;20</td>
<td>&gt;20</td>
</tr>
</tbody>
</table>
</div>
<blockquote class="blockquote">
<p>Voorbeeld</p>
<p>Matig veel zeer fijne, weinig fijne, zeer weinig medium en geen grove wortels</p>
</blockquote>
</section>
</section>
<section id="sporen-van-dierenactiviteit" class="level3" data-number="4.9.4">
<h3 data-number="4.9.4" class="anchored" data-anchor-id="sporen-van-dierenactiviteit"><span class="header-section-number">4.9.4</span> Sporen van dierenactiviteit</h3>
<section id="type-van-dierenactiviteit" class="level4" data-number="4.9.4.1">
<h4 data-number="4.9.4.1" class="anchored" data-anchor-id="type-van-dierenactiviteit"><span class="header-section-number">4.9.4.1</span> Type van dierenactiviteit</h4>
<p>Indien mogelijk kan het type dierenactiviteit worden beschreven.</p>
<blockquote class="blockquote">
<p>Voorbeelden</p>
<ul>
<li>Mollengang, molshoop</li>
<li>Regenwormkanaal, regenwormuitwerpselen</li>
<li>Crotovina (galerij opgevuld met uitwerpselen van talrijke soorten dieren, inclusief regenwormen)</li>
<li>Galerijen van grotere zoogdieren als konijnen en dassen</li>
<li>Mierengang en -nest</li>
<li>Andere insectenactiviteit (bv. mestkevers)</li>
<li>Andere (definieer)</li>
</ul>
</blockquote>
</section>
<section id="concentratie" class="level4" data-number="4.9.4.2">
<h4 data-number="4.9.4.2" class="anchored" data-anchor-id="concentratie"><span class="header-section-number">4.9.4.2</span> Concentratie</h4>
<p>Maak een schatting van het aantal sporen van biologische activiteit als een percentage van de oppervlakte of tel in aantallen per vierkante meter (<a href="#tbl-04-20">tabel&nbsp;<span>4.20</span></a>). De voorkeur gaat hier naar een horizontaal vlak voor verticale graafactiviteit (grote regenwormen).</p>
<div id="tbl-04-20" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.20: Categorieën voor de concentratie aan biogalerijen in de bodem.</caption>
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geen</td>
</tr>
<tr class="even">
<td>Zeer weinig (0-2 %)</td>
</tr>
<tr class="odd">
<td>Weinig (2-5 %)</td>
</tr>
<tr class="even">
<td>Vaak (5-15 %)</td>
</tr>
<tr class="odd">
<td>Veel (15-40 %)</td>
</tr>
<tr class="even">
<td>Zeer veel (\40 %)</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="toestand" class="level4" data-number="4.9.4.3">
<h4 data-number="4.9.4.3" class="anchored" data-anchor-id="toestand"><span class="header-section-number">4.9.4.3</span> Toestand</h4>
<p>Noteer of de faunagalerijen open of opgevuld zijn en of de biogalerijen abrupt stoppen (afgetopt zijn).</p>
</section>
<section id="geassocieerde-kennmerken" class="level4" data-number="4.9.4.4">
<h4 data-number="4.9.4.4" class="anchored" data-anchor-id="geassocieerde-kennmerken"><span class="header-section-number">4.9.4.4</span> Geassocieerde kennmerken</h4>
<p>Wortelpenetratie, oxido-reductie langs wanden (ontijzering, neerslag van ijzer, van mangaan)</p>
</section>
</section>
<section id="kalkreactie-met-hcl-carbonaten" class="level3" data-number="4.9.5">
<h3 data-number="4.9.5" class="anchored" data-anchor-id="kalkreactie-met-hcl-carbonaten"><span class="header-section-number">4.9.5</span> Kalkreactie met HCl (carbonaten)</h3>
<p>De aanwezigheid van carbonaten stel je vast door enkele druppels van een zuur (waterstofchloride,10% HCl) aan een bodemmonster toe te voegen. Gebruik hiervoor een flesje voorzien van een druppelteller. HCl kan je in de handel kopen en dien je te verdunnen met gedistilleerd of gedemineraliseerd water tot een concentratie van ongeveer 10%. Wanneer carbonaten aanwezig zijn, zal het monster opbruisen/“reageren” met de vorming van schuim ten gevolge van de productie van CO<sub>2</sub> gas. De exacte hoeveelheid carbonaten wordt, indien nodig voor verder onderzoek, in het laboratorium bepaald. De kalk kan afkomstig zijn van bijvoorbeeld schelpen, mortel, cement, wortelgroei en pseudomycelium, kalkaanrijking vanuit het grondwater, etc.</p>
<ul>
<li><p>Welke horizonten in de bodem zijn kalkrijk?</p>
<ul>
<li>Als er sporen van kalk in ten minste één aardkundige eenheid van het bodemprofiel worden gevonden, is het aangeraden de aanwezigheid/afwezigheid ervan voor alle eenheden te registreren.</li>
</ul></li>
<li><p>Waar zit de kalk in de bodemhorizont?</p>
<ul>
<li>Noteer of er kalkrijke elementen zijn, dus waar zit de kalk (bv. in de poriën, in de antropogene elementen zoals kalkmortelbrokken, in de matrix…)</li>
</ul></li>
<li><p>Is de kalk primair of secundair?</p>
<ul>
<li>Carbonaten komen voor in bodems onder primaire vorm (moedermateriaal, bijvoorbeeld in löss) en secundaire vorm (concreties, nodules), als gevolg van oplossing en opnieuw neerslaan als deel van de bodemvorming. Het is belangrijk deze twee vormen te onderscheiden.</li>
</ul></li>
<li><p>Kalkklassen na toevoegen HCl, volgende categorieën kunnen toegepast worden (<a href="#tbl-04-21">tabel&nbsp;<span>4.21</span></a>).</p></li>
</ul>
<div id="tbl-04-21" class="anchored">
<table class="table">
<caption>Tabel&nbsp;4.21: De klassen aan kalkconcentratie in de bodem.</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th>Categorie</th>
<th>Omschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kalkloos</td>
<td>Geen hoorbare of zichtbare reactie</td>
</tr>
<tr class="even">
<td>Licht kalkrijk</td>
<td>De reactie is enkel hoorbaar</td>
</tr>
<tr class="odd">
<td>Matig kalkrijk</td>
<td>Opbruising, de reactie is ook zichtbaar</td>
</tr>
<tr class="even">
<td>Sterk kalkrijk</td>
<td>Heel sterk opbruisend, bubbels vormen een lage schuimlaag</td>
</tr>
<tr class="odd">
<td>Extreem kalkrijk</td>
<td>Extreem sterke opbruising, de bubbels vormen snel een dikke schuimlaag</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="accumulatie-van-ijzer-en-mangaan" class="level3" data-number="4.9.6">
<h3 data-number="4.9.6" class="anchored" data-anchor-id="accumulatie-van-ijzer-en-mangaan"><span class="header-section-number">4.9.6</span> Accumulatie van ijzer en mangaan</h3>
<p>IJzer en mangaan kunnen in bijzondere milieucondities (in een reducerend of zuurstofarm milieu) oplossen, (dit proces zal vooral uitgesproken zijn in zure bodems), migreren en ten slotte neerslaan in zones waar terug zuurstof aanwezig is (oxidatie).</p>
<p>Zeker vier vormen van neerslag kunnen voorkomen:</p>
<ul>
<li><p>Een aanrijking van de bodemmatrix onder de vorm van “vlekken” of zones van concentraties (<a href="#fig-04-15">fig.&nbsp;<span>4.15</span></a>);</p></li>
<li><p>Concreties: een concentrische sferoïdale vorm, meestal gecementeerd (<a href="#fig-04-16">fig.&nbsp;<span>4.16</span></a>);</p></li>
<li><p>Nodules: knobbels zonder concentrische vorm;</p></li>
<li><p>Huidjes: op structuurvlakken en langs galerijen of poriën (<a href="#fig-04-17">fig.&nbsp;<span>4.17</span></a>)</p></li>
</ul>
<div id="fig-04-15" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figuren/image73.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figuur&nbsp;4.15: Concentratie van mangaan (zwarte pijlen) en van ijzer (rode pijlen) als gevolg van oxido-reductie. De sterke instulping rechts van de meter is een karrespoor. Karolingische periode, ijzerontginning met laagovens in het Zoniënwoud. (copyright en foto Jari Mikkelsen).</figcaption>
</figure>
</div>
<div id="fig-04-16" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="figuren/image74.jpeg" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="figuren/image75.jpeg" class="img-fluid figure-img"></p>
</div>
</div>
<p></p><figcaption class="figure-caption">Figuur&nbsp;4.16: Concentratie van mangaan en ijzer als gevolg van oxido-reductie. Lokaal zijn ijzerconcreties gevormd (rode pijlen) (copyright en foto’s Jari Mikkelsen).</figcaption><p></p>
</figure>
</div>
<div id="fig-04-17" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="figuren/image76.jpeg" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="figuren/image77.jpeg" class="img-fluid figure-img"></p>
</div>
</div>
<p></p><figcaption class="figure-caption">Figuur&nbsp;4.17: Boven voorbeeld van klei-ijzerhuidjes op structuurvlakken, onder klei-humushuidjes in een wormgang. Deze voorbeelden zijn erg duidelijk, meestal zijn ze iets subtieler (copyright en foto’s: Stefaan Dondeyne).</figcaption><p></p>
</figure>
</div>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Speciale kleurkaart voor kleuren van zuurstofarm, sterk gereduceerd bodemmateriaal (gleykleuren)<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Speciale kleurkaart voor glauconiethoudende bodems<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Speciale kleurkaart voor kalk, silica, pleister, gips, zout etc.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp("https:\/\/hanecakr\.github\.io\/handleidingBeschrijvenBodems\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_bodemvorming.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bodemvormende factoren</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_classificatie.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Classificatie van het bodemprofiel</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>